version: 2
updates:
  - package-ecosystem: "pub"
    target-branch: master
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    target-branch: master
    directory: "/android"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    target-branch: master
    directory: "/"
    schedule:
      interval: "weekly"
